name: Build EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Show public IP
        run: curl https://ipinfo.io

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Install project requirements
        run: pip install -r requirements.txt

      - name: Build EXE
        run: |
          pyinstaller `
          --noconfirm `
          --onefile `
          --windowed `
          --name FL_Foreclosure_Scraper `
          --add-data "Animation;Animation" `
          --add-data "utils;utils" `
          --add-data "db;db" `
          --icon Animation/icon.ico `
          main.py

      - name: Force tag to v1.2
        run: |
          git tag -f v1.2
          git push -f origin v1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to existing release (replace file)
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.2
          files: dist/FL_Foreclosure_Scraper.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
